prod yaml file

diff --git a/.github/workflows/prod.yaml b/.github/workflows/prod.yaml
--- a/.github/workflows/prod.yaml
+++ b/.github/workflows/prod.yaml
@@ -2,16 +2,22 @@ name: Prod build and deployment
 on:
   push:
     branches:
-      - 'main'
+      - 'origin/master'
 jobs:
   BuildSimulation:
-    # TODO abort this workflow if the git user triggered it is not the release manager
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+      - name: Check Release Manager
+        id: check_release_manager
+        run: |
+          if [[ "${{ github.actor }}" != "AmiranIV" ]]; then
+            echo "Workflow aborted. Only the release manager can trigger this workflow."
+            exit 1
+          fi
       - name: Build
         run: |
-          echo building and packing and app...
+          echo "Building and packing an app..."
   DeploySimulation:
     runs-on: ubuntu-latest
     needs: BuildSimulation
@@ -19,4 +25,4 @@ jobs:
       - uses: actions/checkout@v3
       - name: Deploy
         run: |
-          echo deploying into Test env
+          echo "Deploying into Test environment"
